import { Link } from "react-router-dom";
import * as ConfidentialModeStyle from "./ConfidentialModeStyle";
import { MdArrowDropDown } from "react-icons/md";
import { IoMdHelpCircleOutline } from "react-icons/io";
import { BtnPrimary, BtnSecondary, Icon } from "../../components";
import { useCompose } from "../../hooks";
import ConfidentialModeExpire from "../confidentialModeExpire/ConfidentialModeExpire";
import { currentDate } from "../confidentialModeExpire/confidentialModeParams";
import { useState } from "react";

const ConfidentialMode = () => {
	const { useComposeMessage } = useCompose();

	const [isNoSMSPasscode, setNoSMSPasscode] = useState(false);
	const [isSMSPasscode, setSMSPasscode] = useState(false);

	return (
		<>
			<ConfidentialModeStyle.ConfidentialModeWrapper>
				<ConfidentialModeStyle.ConfidentialModeContainer>
					<ConfidentialModeStyle.ConfidentialModeHeading>Confidential mode</ConfidentialModeStyle.ConfidentialModeHeading>

					<p>
						Recipients won't have the option to forward, copy, print, or download this email. {""}
						<Link to="https://support.google.com/mail/answer/7674059?hl=en">Learn more</Link>
					</p>

					<ConfidentialModeStyle.ConfidentialModeSubHeading>set expiration</ConfidentialModeStyle.ConfidentialModeSubHeading>

					<ConfidentialModeStyle.ConfidentialModeTimeWrapper>
						<ConfidentialModeStyle.ConfidentialModeTimeCategory className="col" onClick={useComposeMessage.setConfidentialModeExpireOn}>
							<div>{useComposeMessage.confidentialModeExpireTime ? useComposeMessage.confidentialModeExpireTime : "Expires in 1 week"}</div>

							<MdArrowDropDown />
						</ConfidentialModeStyle.ConfidentialModeTimeCategory>

						<div className="col">{useComposeMessage.confidentialModeExpireNextTime ? useComposeMessage.confidentialModeExpireNextTime : currentDate}</div>
					</ConfidentialModeStyle.ConfidentialModeTimeWrapper>

					<div>
						<ConfidentialModeStyle.ConfidentialModeSubHeading>require passcode</ConfidentialModeStyle.ConfidentialModeSubHeading>

						<ConfidentialModeStyle.ConfidentialModePasscodeWrapper>
							<span>All passcodes will be generated by Google.</span>
							<div>
								<Icon>
									<IoMdHelpCircleOutline size={22} color="rgb(32, 33, 36)" />
								</Icon>
							</div>
						</ConfidentialModeStyle.ConfidentialModePasscodeWrapper>
					</div>

					<ConfidentialModeStyle.ConfidentialModeSMSPasscodeWrapper>
						<ConfidentialModeStyle.ConfidentialModeRadioWrapper className="col me-3" smsChecked={isNoSMSPasscode.toString()}>
							<div
								className="d-flex align-items-center"
								onClick={() => {
									setNoSMSPasscode(true);
									setSMSPasscode(false);
								}}>
								<div className="inputContainer">
									<input
										type="radio"
										name="sms"
										id="noSMS"
										checked={isNoSMSPasscode}
										onChange={() => {
											setNoSMSPasscode(true);
											setSMSPasscode(false);
										}}
									/>
								</div>

								<span>No SMS passcode</span>
							</div>
						</ConfidentialModeStyle.ConfidentialModeRadioWrapper>

						<ConfidentialModeStyle.ConfidentialModeRadioWrapper className="col" smsChecked={isSMSPasscode.toString()}>
							<div
								className="d-flex align-items-center"
								onClick={() => {
									setSMSPasscode(true);
									setNoSMSPasscode(false);
								}}>
								<div className="inputContainer">
									<input
										type="radio"
										name="sms"
										id="SMS"
										checked={isSMSPasscode}
										onChange={() => {
											setSMSPasscode(true);
											setNoSMSPasscode(false);
										}}
									/>
								</div>

								<span>SMS passcode</span>
							</div>
						</ConfidentialModeStyle.ConfidentialModeRadioWrapper>
					</ConfidentialModeStyle.ConfidentialModeSMSPasscodeWrapper>

					<ConfidentialModeStyle.ConfidentialModeBtnWrapper>
						<ConfidentialModeStyle.ConfidentialModeBtnContainer onClick={useComposeMessage.setConfidentialModeOff}>
							<BtnSecondary name="Cancel" borderRadius="20px" />
						</ConfidentialModeStyle.ConfidentialModeBtnContainer>

						<ConfidentialModeStyle.ConfidentialModeBtnContainer onClick={useComposeMessage.setConfidentialModeTimeShowOn}>
							<BtnPrimary name="Save" borderRadius="20px" padding="7.5px 25px" />
						</ConfidentialModeStyle.ConfidentialModeBtnContainer>
					</ConfidentialModeStyle.ConfidentialModeBtnWrapper>

					{useComposeMessage.confidentialModeExpireState && <ConfidentialModeExpire />}
				</ConfidentialModeStyle.ConfidentialModeContainer>
			</ConfidentialModeStyle.ConfidentialModeWrapper>
		</>
	);
};

export default ConfidentialMode;
