import {
	AccountPhoto,
	GoogleIcon,
	GoogleMap,
	YoutubeIcon,
	GooglePlayStoreIcon,
	GoogleNewsIcon,
	GoogleGmailIcon,
	GoogleMeetIcon,
	GoogleChatIcon,
	GoogleContactsIcon,
	GoogleDriveIcon,
	GoogleCalenderIcon,
	GoogleTranslateIcon,
	GooglePhotoIcon,
	GoogleMyAddCenterIcon,
	GoogleShoppingIcon,
	GoogleFinanceIcon,
	GoogleDocsIcon,
	GoogleSheetsIcon,
	GoogleSlidesIcon,
	GoogleBooksIcon,
	GoogleBloggerIcon,
	GoogleKeepIcon,
	GoogleJamboardIcon,
	GoogleClassroomIcon,
	GoogleEarthIcon,
	GoogleSavedIcon,
	GoogleArtAndCultureIcon,
	GoogleAdsIcon,
	GoogleOneIcon,
	GoogleTravelIcon,
	GoogleFormsIcon,
	GoogleStoreIcon,
	GoogleVoiceIcon,
	GoogleChromeWebStoreIcon,
	GoogleFiWirelessIcon,
	GooglePasswordIcon,
} from "../../assets";

const apps = [
	{ image: AccountPhoto, name: "Account", link: "", height: "4rem" },
	{ image: GoogleIcon, name: "Search", link: "https://www.google.com", height: "4rem" },
	{ image: GoogleMap, name: "Maps", link: "https://www.google.com/maps", height: "4rem" },
	{ image: YoutubeIcon, name: "YouTube", link: "https://www.youtube.com/" },
	{ image: GooglePlayStoreIcon, name: "Play", link: "https://play.google.com/store/" },
	{ image: GoogleNewsIcon, name: "News", link: "https://news.google.com/" },
	{ image: GoogleGmailIcon, name: "Gmail", link: "https://mail.google.com/", height: "3.8rem" },
	{ image: GoogleMeetIcon, name: "Meet", link: "https://meet.google.com/" },
	{ image: GoogleChatIcon, name: "Chat", link: "https://mail.google.com/chat", height: "4.5rem" },
	{ image: GoogleContactsIcon, name: "Contacts", link: "https://contacts.google.com/", height: "3.8rem" },
	{ image: GoogleDriveIcon, name: "Drive", link: "https://drive.google.com/" },
	{ image: GoogleCalenderIcon, name: "Calendar", link: "https://calendar.google.com/", height: "3.8rem" },
	{ image: GoogleTranslateIcon, name: "Translate", link: "https://translate.google.com/" },
	{ image: GooglePhotoIcon, name: "Photos", link: "https://photos.google.com/", height: "3.8rem" },
	{ image: GoogleMyAddCenterIcon, name: "My Ad Center", link: "https://myadcenter.google.com/" },
	{ image: GoogleShoppingIcon, name: "Shopping", link: "https://shopping.google.com/", height: "5rem" },
];

const apps2 = [
	{ image: GoogleFinanceIcon, name: "Finance", link: "https://www.google.com/finance/" },
	{ image: GoogleDocsIcon, name: "Docs", link: "https://docs.google.com/documents" },
	{ image: GoogleSheetsIcon, name: "Sheets", link: "https://docs.google.com/spreadsheets/" },
	{ image: GoogleSlidesIcon, name: "Slides", link: "https://docs.google.com/presentation/" },
	{ image: GoogleBooksIcon, name: "Books", link: "https://books.google.com/" },
	{ image: GoogleBloggerIcon, name: "Blogger", link: "https://www.blogger.com/" },
	{ image: GoogleKeepIcon, name: "Keep", link: "https://keep.google.com/" },
	{ image: GoogleJamboardIcon, name: "Jamboard", link: "https://jamboard.google.com/" },
	{ image: GoogleClassroomIcon, name: "Classroom", link: "https://classroom.google.com/" },
	{ image: GoogleEarthIcon, name: "Earth", link: "https://earth.google.com/" },
	{ image: GoogleSavedIcon, name: "Saved", link: "https://www.google.com/interests/saved" },
	{ image: GoogleArtAndCultureIcon, name: "Arts and Culture", link: "https://artsandculture.google.com/" },
	{ image: GoogleAdsIcon, name: "Google Ads", link: "https://ads.google.com/" },
	{ image: GoogleOneIcon, name: "Google One", link: "https://one.google.com/" },
	{ image: GoogleTravelIcon, name: "Travel", link: "https://www.google.com/travel/" },
	{ image: GoogleFormsIcon, name: "Forms", link: "https://docs.google.com/forms" },
	{ image: GoogleStoreIcon, name: "Google Store", link: "https://store.google.com/" },
	{ image: GoogleVoiceIcon, name: "Voice", link: "https://voice.google.com/" },
	{ image: GoogleChromeWebStoreIcon, name: "Chrome Web Store", link: "https://chromewebstore.google.com/" },
	{ image: GoogleFiWirelessIcon, name: "Google Fi Wireless", link: "https://fi.google.com/about/" },
	{ image: GooglePasswordIcon, name: "Password Manager", link: "https://passwords.google.com/" },
];

export { apps, apps2 };
